services:

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
        - ./postgres-db-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
